### ISSUE TITLE
Update Selenium dependency

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-behat-extension#137]
This module's `composer.json` currently has these requirements:

```
"behat/behat": "~2.5.0",
"behat/mink": "~1.6.0",
"behat/mink-extension": "~1.3.0",
"behat/mink-selenium2-driver": "~1.2.0",
```

The README recommends the following:

> Now get the latest Selenium2 server (requires Java): wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
...
> Download the latest Firefox ESR (Extended Support Release). It might be older than your currently installed Firefox. It's important to have a browser that's supported by Selenium-Webdriver

The [latest Selenium](http://selenium-release.storage.googleapis.com/index.html) release is 2.53. The [latest Firefox ESR](https://www.mozilla.org/en-US/firefox/45.6.0/releasenotes/) is 45.0.

The [Behat/Mink2SeleniumDriver](https://github.com/Behat/MinkSelenium2Driver) does not limit Selenium compat.

Technically, this should allow us to upgrade to the latest Selenium.

**Comment by tractorcow** [comment]
Yes, but you'll run into bugs that appear discretely. Later versions of selenium have issues interacting with some later versions of firefox.

Input fields get concatenated rather than replaced in some instances, for example.

I suspect the issue would be with the version of the mink-selenium2 driver we are on, but upgrading further would be a mess of upgrades that eventuates in us needing to upgrade to behat 3.

**Comment by tractorcow** [comment]
We've now updated to behat 3. We should prioritise this.

**Comment by tractorcow** [comment]
@chillu pinging to confirm this should be beta2.

**Comment by dhensby** [comment]
Perhaps this is why trusty doesn't work? https://github.com/silverstripe/silverstripe-framework/pull/7092

**Comment by tractorcow** [comment]
At the moment, there are a bunch of repos that partially work with behat, and some that don't. It appears that modules are being migrated across travis, so while some modules may appear to work for now, we can probably expect them to break UNLESS we move to trusty.

I don't know why everything is broken, but have been experimenting with upgrading firefox / selenium / mink (and various combinations of such) to get it working again.

**Comment by chillu** [comment]
Removing this from the milestone, since the short term solution was much simpler: Switch to trusty and pin the firefox release. There's still value in getting on the current 3.x Selenium version for Behat, but the underlying ecosystem doesn't support this well. There's an experimental Mink driver for headless Chrome use without going through Selenium, which would be much more interesting to us in terms of dev experience - so happy to wait a bit with this upgrade.

**Comment by tractorcow** [comment]
I've setup a fork of mink-selenium2-driver, and re-vendored it.

My project composer.json for this project is as below (and I'll update as I go along).

```json
{
    "name": "silverstripe/installer",
    "type": "silverstripe-recipe",
    "description": "The SilverStripe Framework Installer",
    "require": {
        "php": ">=5.6.0",
        "silverstripe/recipe-plugin": "^1",
        "silverstripe/recipe-cms": "1.0.x-dev",
        "silverstripe-themes/simple": "~3.2.0",
        "silverstripe/serve": "^2",
        "se/selenium-server-standalone": "^3",
        "silverstripe/behat-extension": "dev-pulls/4.0/selenium-upgrade as 3.1.x-dev",
        "silverstripe/mink-selenium3-driver": "dev-master"
    },
    "repositories": {
        "seleniumdriver": {
            "type": "vcs",
            "url": "https://github.com/open-sausages/MinkSelenium3Driver.git"
        },
        "behat-extension": {
            "type": "vcs",
            "url": "https://github.com/open-sausages/silverstripe-behat-extension.git"
        }
    },
    "config": {
        "process-timeout": 600
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}

```

**Comment by tractorcow** [comment]
Progress so far:
 - framework behat green
 - cms behat green

To do:
 - asset-admin
 - campaign admin
 - travis setup

**Comment by tractorcow** [comment]
@ingo ready to review.

**Comment by tractorcow** [comment]
Root behat.yml to use.


```yaml
# Note: Currently chrome latest is recommended
# Behat test setup requires an `.env` with `SS_BASE_URL` defined, as well
# as each of the following commands to initiate a test run:
# ========================================================================= #
# composer require silverstripe/recipe-testing ^1
# vendor/bin/behat-ss @<module>
# ========================================================================= #
default:
  suites: []
  extensions:
    SilverStripe\BehatExtension\MinkExtension:
      default_session: facebook_web_driver
      javascript_session: facebook_web_driver
      facebook_web_driver:
        browser: chrome
        wd_host: "http://127.0.0.1:9515" #chromedriver port
      browser_name: chrome
    SilverStripe\BehatExtension\Extension:
      bootstrap_file: vendor/silverstripe/cms/tests/behat/serve-bootstrap.php
      screenshot_path: %paths.base%/artifacts/screenshots
      retry_seconds: 4 # default is 2

```
