### ISSUE TITLE
Issue using headless Chrome

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-behat-extension#168]
OK, so I'm stuck using ~1.0 because I'm using framework 3.6 - all is working, but a heads-up for using Chrome as a headless browser (v59+) that in `SilverStripeContext::before()` you obviously cannot resize a window that isn't there ala

```
        if ($screenSize = getenv('BEHAT_SCREEN_SIZE')) {
            list($screenWidth, $screenHeight) = explode('x', $screenSize);
            $this->getSession()->resizeWindow((int)$screenWidth, (int)$screenHeight);
        } else {
            $this->getSession()->resizeWindow(1024, 768);
        }
```

If I comment this block out, all is well in the world, but leaving it as-is, makes my terminal go blood-red! Sure, in headless mode, AFAIK I cannot - and there would be no point in - running tests that exercise mobile/handlheld specific UIs, but I can live with that for now.

There's probably a way of extracting the "switches" config out of Mink and passing that around in a condition, but I wouldn't know anything about that...:-P

```
default:
  context:
    class: 'App\Test\Behaviour\FeatureContext'
  extensions:
    SilverStripe\BehatExtension\Extension:
      screenshot_path: %behat.paths.base%/artifacts/screenshots
    SilverStripe\BehatExtension\MinkExtension:
      base_url: 'http://localhost'
      default_session: selenium2
      javascript_session: selenium2
      selenium2:
        browser: chrome
        capabilities:
          browser: chrome
          platform: Linux
          chrome:
            # Lose your head!
            switches:
              - '--headless'
              - '--disable-gpu'
```
